### ISSUE TITLE
my advice for good architecture

### ISSUE THREAD

**Issue by Alex777Russia** [Anjleil/LeetCode-Solutions#1]
Ты в любом случае будешь решать большое количество задач, а следовательно и стараться загружать будешь все.
Если они все будут находиться на верхнем уровне, то будет сложно ориентироваться и искать нужные.
К тому же это не очень красиво.

Сделай различение на директории задач, например:
- сложность
> easy 
> medium 
> hard
- типы задач
> массивы
> списки
> деревья
> динамическое программировани
- ну или по номеру задач
> 1-100
> 101-200
> 1001-1100

Вот примерно как-то так

**Comment by Anjleil** [comment]
Чел ты

**Comment by Alex777Russia** [comment]
Жесть чел мотивирован, респект
